src/MvcMusicStore/Controllers/StoreManagerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcMusicStore.Models;
using MvcMusicStore.ViewModels;

namespace MvcMusicStore.Controllers {
    public class StoreManagerController : Controller {
        private MusicStoreEntities db = new MusicStoreEntities();

private void SetGenreArtistViewBag(int? GenreID = null, int? ArtistID = null) {

    if (GenreID == null)
        ViewBag.Genres = new SelectList(db.Genres, "GenreId", "Name");
    else
        ViewBag.Genres = new SelectList(db.Genres.ToArray(), "GenreId", "Name", GenreID);

    if (ArtistID == null)
        ViewBag.Artists = new SelectList(db.Artists, "ArtistId", "Name");
    else
        ViewBag.Artists = new SelectList(db.Artists, "ArtistId", "Name", ArtistID);

}
        //
        // GET: /StoreManager/

        public ViewResult Index() {
            var albums = db.Albums.Include(a => a.Genre).Include(a => a.Artist)
                .OrderBy(a => a.Price);
            return View(albums.ToList());
        }

        //
        // GET: /StoreManager/Details/5

        public ViewResult Details(int id) {
            Album album = db.Albums.Find(id);
            return View(album);
        }

//
// GET: /StoreManager/Create

public ActionResult Create() {
    SetGenreArtistViewBag();
    //var album = new Album { Price = 1.23M };
    return View();
}


//
// POST: /StoreManager/Create

[HttpPost]
public ActionResult Create(Album album) {
    if (ModelState.IsValid) {
        db.Albums.Add(album);
        db.SaveChanges();
        return RedirectToAction("Index");
    }
    SetGenreArtistViewBag(album.GenreId, album.ArtistId);
    return View(album);
}

//
// GET: /StoreManager/Edit/5

public ActionResult Edit(int id) {
    Album album = db.Albums.Find(id);
    SetGenreArtistViewBag(album.GenreId, album.ArtistId);
    return View(album);
}

//
// POST: /StoreManager/Edit/5

[HttpPost]
public ActionResult Edit(Album album) {
    if (ModelState.IsValid) {
        db.Entry(album).State = EntityState.Modified;
        db.SaveChanges();
        return RedirectToAction("Index");
    }
    SetGenreArtistViewBag(album.GenreId, album.ArtistId);
    return View(album);
}

//
// GET: /StoreManager/EditVM/5

public ActionResult EditVM(int id) {
    Album album = db.Albums.Find(id);
    if (album == null)
        return HttpNotFound();

    AlbumSelectListViewModel aslvm = new AlbumSelectListViewModel(album, db.Artists, db.Genres);
    return View(aslvm);
}

        //
        // GET: /StoreManager/Delete/5

        public ActionResult Delete(int id) {
            Album album = db.Albums.Find(id);
            return View(album);
        }

        //
        // POST: /StoreManager/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id) {
            Album album = db.Albums.Find(id);
            db.Albums.Remove(album);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing) {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

src/MvcMusicStore/Views/StoreManager/Create.cshtml
@model MvcMusicStore.Models.Album

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
<legend>Album</legend>


<div class="editor-field ui-widget">
     @Html.Partial("_ChooseGenre")
</div>

<div class="editor-field ui-widget">
     @Html.Partial("_ChooseArtist")
</div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Price)
            @Html.ValidationMessageFor(model => model.Price)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.AlbumArtUrl)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AlbumArtUrl)
            @Html.ValidationMessageFor(model => model.AlbumArtUrl)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

src/MvcMusicStore/Views/StoreManager/Delete.cshtml
@model MvcMusicStore.Models.Album

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Album</legend>

    <div class="display-label">Genre</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Genre.Name)
    </div>

    <div class="display-label">Artist</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Artist.Name)
    </div>

    <div class="display-label">Title</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">Price</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Price)
    </div>

    <div class="display-label">AlbumArtUrl</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AlbumArtUrl)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

src/MvcMusicStore/Views/StoreManager/Details.cshtml
@model MvcMusicStore.Models.Album

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Album</legend>

    <div class="display-label">Genre</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Genre.Name)
    </div>

    <div class="display-label">Artist</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Artist.Name)
    </div>

    <div class="display-label">Title</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">Price</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Price)
    </div>

    <div class="display-label">AlbumArtUrl</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AlbumArtUrl)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.AlbumId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

src/MvcMusicStore/Views/StoreManager/Edit.cshtml
@model MvcMusicStore.Models.Album

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Album</legend>

        @Html.HiddenFor(model => model.AlbumId)
@*           No need to pass String.Empty) given a selected value. String.Empty is required in the Create view.
            @Html.DropDownList("GenreId", String.Empty)
            @Html.DropDownList("GenreId") *@

   <div class="editor-field ui-widget">
     @Html.Partial("_ChooseGenre")
</div>

<div class="editor-field ui-widget">
     @Html.Partial("_ChooseArtist")
</div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Price)
            @Html.ValidationMessageFor(model => model.Price)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.AlbumArtUrl)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AlbumArtUrl)
            @Html.ValidationMessageFor(model => model.AlbumArtUrl)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

src/MvcMusicStore/Views/StoreManager/EditVM.cshtml
@model MvcMusicStore.ViewModels.AlbumSelectListViewModel

@{
    ViewBag.Title = "EditVM";
}

<h2>Edit VM</h2>

@using (Html.BeginForm("Edit","StoreManager",FormMethod.Post)) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Album</legend>

        @Html.HiddenFor(model => model.Album.AlbumId )

        <div class="editor-label">
            @Html.LabelFor(model => model.Album.GenreId, "Genre")
        </div>
        <div class="editor-field">
            @Html.DropDownList("Album.GenreId", Model.Genres)
            @Html.ValidationMessageFor(model => model.Album.GenreId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Album.ArtistId, "Artist")
        </div>
        <div class="editor-field">
            @Html.DropDownList("Album.ArtistId", Model.Artists)
            @Html.ValidationMessageFor(model => model.Album.ArtistId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Album.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Album.Title)
            @Html.ValidationMessageFor(model => model.Album.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Album.Price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Album.Price)
            @Html.ValidationMessageFor(model => model.Album.Price)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Album.AlbumArtUrl)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Album.AlbumArtUrl)
            @Html.ValidationMessageFor(model => model.Album.AlbumArtUrl)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

src/MvcMusicStore/Views/StoreManager/Index.cshtml
@model IEnumerable<MvcMusicStore.Models.Album>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            Genre
        </th>
        <th>
            Artist
        </th>
        <th>
            Title
        </th>
        <th>
            Price
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Genre.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Artist.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.AlbumId }) |
            @Html.ActionLink("Details", "Details", new { id=item.AlbumId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.AlbumId })
        </td>
    </tr>
}

</table>

src/MvcMusicStore/Views/StoreManager/_ChooseArtist.cshtml
@model MvcMusicStore.Models.Album
 <div class="editor-label">
    @Html.LabelFor(model => model.ArtistId, "Artist" )
</div>
@Html.DropDownList("ArtistId", ViewBag.Artists as SelectList,String.Empty)
<a class="button" href="@Url.Content("~/Artist/Create")" 
    id="artistAddLink">Add New Artist</a>
@Html.ValidationMessageFor(model => model.ArtistId)
<div id="artistDialog" class="hidden">
</div>

<script src="@Url.Content( "~/Scripts/ui/jquery.ui.combobox.js" )"></script>
<script src="@Url.Content("~/Scripts/chooseArtist.js")"></script>

src/MvcMusicStore/Views/StoreManager/_ChooseGenre.cshtml
@model MvcMusicStore.Models.Album
 <div class="editor-label">
    @Html.LabelFor(model => model.GenreId, "Genre" )
</div>
@Html.DropDownList("GenreId", ViewBag.Genres as SelectList,String.Empty)
<a class="button" href="@Url.Content("~/Genre/Create")" 
    id="genreAddLink">Add New Genre</a>
@Html.ValidationMessageFor(model => model.GenreId)
<div id="genreDialog" class="hidden">
</div>

<script src="@Url.Content( "~/Scripts/ui/jquery.ui.combobox.js" )"></script>
<script src="@Url.Content("~/Scripts/chooseGenre.js")"></script>